version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: pgsql-server
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:8-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    # Configuration optimized for small web scraper cache (<500 JSONs)
    command: redis-server --maxmemory 4096mb --maxmemory-policy allkeys-lru --save 180 1 --save 120 10 --save 60 25
    volumes:
      - redis-data:/data
    networks:
      - postgres-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-ui
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - postgres-network
    restart: unless-stopped
    depends_on:
      - postgres

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight-ui
    ports:
      - "5540:5540"
    volumes:
      - redisinsight-data:/data
    networks:
      - postgres-network
    restart: unless-stopped
    depends_on:
      - redis

networks:
  postgres-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local
  pgadmin-data:
    driver: local
  redisinsight-data:
    driver: local
